<?php
/**
 *
 * @url        http://www.tux-tips.de/
 * @license    GPL 2 (http://www.gnu.org/licenses/gpl.html)
 * @author     dan.kreiser <dan.kreiser@gmail.com>
 */

if(!defined('DOKU_INC')) define('DOKU_INC',realpath(dirname(__FILE__).'/../../').'/');
if(!defined('DOKU_PLUGIN')) define('DOKU_PLUGIN',DOKU_INC.'lib/plugins/');
require_once(DOKU_PLUGIN.'syntax.php');

class Syntax_Plugin_symbols extends DokuWiki_Syntax_Plugin {

    function getInfo() {
        return array(
            'author' => 'Dan Kreiser',
            'email'  => 'dan-kreiser@gmail.com',
            'date'   => '2011-03-01',
            'name'   => 'symbols',
            'desc'   => 'display some small symbols',
            'url'    => 'http://www.tux-tips.de/tux-wiki/doku.php?id=start:dokuwiki:plugins',
        );
    }

     /**
     * What kind of syntax are we?
     */
    function getType(){
        return 'substition';
    }
 
    /**
     * What can we Do?
     */
    function getAllowedTypes() { 
        return array(); 
    }
 
    /**
     * Where to sort in?
     */
    function getSort(){
        return 999;
    }

 
        function connectTo($mode) {
    /**
     * Etapas Simples Numeradas
     */
         $this->Lexer->addSpecialPattern('i-mp-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-24',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-25',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-26',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-27',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-28',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-29',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-30',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-31',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-32',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-33',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-34',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-35',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-36',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-37',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-38',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-39',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-40',$mode,'plugin_symbols');

    /**
     * Etapas Especiais
     */
            $this->Lexer->addSpecialPattern('i-mp-inicio',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fim',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ns',$mode,'plugin_symbols');

    /**
     * Variantes do Fluxo de Sa�da
     */
            $this->Lexer->addSpecialPattern('i-mp-se-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-se-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sei-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sei-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sdi-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sdi-ns',$mode,'plugin_symbols');


		 $this->Lexer->addSpecialPattern('i-mp-se-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-sd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sd-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-se-sd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-sd-20',$mode,'plugin_symbols');



    /**
     * Variantes do Fluxo de Entrada
     */
		 $this->Lexer->addSpecialPattern('i-mp-ee-fim',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-fim',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-fim',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-ee-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-ed-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-ed-ns',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-ee-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-24',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-25',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-26',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-27',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-28',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-29',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-30',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-31',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-32',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-33',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-34',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-35',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-36',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-37',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-38',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-39',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-40',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ed-24',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ed-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-inicio',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-inicio',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-inicio',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-inicio',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-inicio',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-edi-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-edi-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-edi-20',$mode,'plugin_symbols');


    /**
     * Variantes de Linhas Secund�rias
     */
            $this->Lexer->addSpecialPattern('i-mp-le-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-se-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-se-ld-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-se-ld-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-se-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-se-ld-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-se-ld-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-22',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-23',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-24',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-25',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-26',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-27',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-28',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-29',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-30',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-31',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-32',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-33',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-34',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-35',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-36',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-37',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-38',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-39',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-40',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-22',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-23',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-24',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-25',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-26',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-27',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-28',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-22',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-23',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-24',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-25',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-ld-ld-26',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-le-ld-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-ld-ld-20',$mode,'plugin_symbols');


    /**
     * Variantes de Fluxos Secund�rios
     */
            $this->Lexer->addSpecialPattern('i-mp-fd-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-sn',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ns',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-22',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-23',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-24',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-25',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-26',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-27',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-28',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-29',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-30',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-21',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-22',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-23',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fd-24',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-fe-ld-20',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-01',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-02',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-03',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-04',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-05',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-06',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-07',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-08',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-09',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-10',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-11',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-12',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-13',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-14',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-15',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-16',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-17',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-18',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-19',$mode,'plugin_symbols');
            $this->Lexer->addSpecialPattern('i-mp-le-fd-20',$mode,'plugin_symbols');


		 $this->Lexer->addSpecialPattern('i-mp-sfe-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfe-ld-20',$mode,'plugin_symbols');



		 $this->Lexer->addSpecialPattern('i-mp-sfd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sfd-20',$mode,'plugin_symbols');


    /**
     * Variantes de Etapas Exc�ntricas
     */

		 $this->Lexer->addSpecialPattern('i-mp-fd-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fd-fd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fd-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fd-fd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-ld-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-sei-ed-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sei-ed-ns',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-be-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bd-24',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-24',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-25',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-26',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-27',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-28',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-29',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-30',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-21',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fc-bd-23',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-bex-fim',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-fim',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-bex-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bex-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-bdx-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-22',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-25',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-bdx-28',$mode,'plugin_symbols');

    /**
     * Combina��es
     */
		 $this->Lexer->addSpecialPattern('i-mp-ee-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-fd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-ed-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-ed-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-ld-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-fe-sd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-sd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-fd-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-ee-fd-fd-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-fd-fd-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-ed-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-fe-fe-ed-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-bex-ld-fim',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-fim',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bdx-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-sei-ld-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-sei-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-sdi-sn',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-sdi-ns',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-sd-inicio',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ld-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-edi-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-edi-20',$mode,'plugin_symbols');


		 $this->Lexer->addSpecialPattern('i-mp-le-bd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-bd-20',$mode,'plugin_symbols');
 		$this->Lexer->addSpecialPattern('i-mp-le-fc-bd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-fc-bd-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-ld-20',$mode,'plugin_symbols');
 		$this->Lexer->addSpecialPattern('i-mp-be-fc-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-be-fc-ld-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ee-ld-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-ld-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-20',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-23',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-ed-25',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-sfd-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-01',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-02',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-03',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-04',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-05',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-06',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-07',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-08',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-09',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-10',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-11',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-12',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-13',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-14',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-15',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-16',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-17',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-18',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-19',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-ee-edi-20',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-eei-ed-27',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-eei-ed-29',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-sdi-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-sdi-ld-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-sei-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-sei-ld-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-le-sdi-ld-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-le-le-sdi-ld-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-se-edi-ns',$mode,'plugin_symbols');
		 $this->Lexer->addSpecialPattern('i-mp-se-edi-sn',$mode,'plugin_symbols');

		 $this->Lexer->addSpecialPattern('i-mp-le-eei-edi-ld-20',$mode,'plugin_symbols');

			}
 
        function handle($match, $state, $pos, &$handler) {
            return array($match);
        }
 
        function render($mode, &$renderer, $data) {
		$name= substr($data[0],2, -5);
		$renderer->doc .= '<img src="'. DOKU_URL .'lib/plugins/symbols/images/toolbar/symbols/' . $data[0] . '.png" style="height:60%" alt="' . $name . '" title="' . $name .'" />';
		return true;
        }

}
